import type { Metadata } from "next";
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import ConvexClientProvider from '@/components/ConvexClientProvider'
import Header from '@/components/Header'
import { Toaster } from 'sonner'
import StoreUserEffect from '@/components/StoreUserEffect'
import { ThemeProvider } from "@/components/theme-provider"
import { DesignPageProvider } from "@/components/DesignPageContext"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <ConvexClientProvider>
            <DesignPageProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <StoreUserEffect />
                <Header />
                <main className="min-h-screen bg-background">
                  {children}
                </main>
                <Toaster />
              </ThemeProvider>
            </DesignPageProvider>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
